//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.09 at 11:09:14 AM EET 
//


package entity;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Category.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Category">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Fitness and aerobics"/>
 *     &lt;enumeration value="Simulators and sports equipment"/>
 *     &lt;enumeration value="Game kinds of sports"/>
 *     &lt;enumeration value="Bicycles, electric bicycles and accessories"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Category")
@XmlEnum
public enum Category {

    @XmlEnumValue("Fitness and aerobics")
    FITNESS_AND_AEROBICS("Fitness and aerobics"),
    @XmlEnumValue("Simulators and sports equipment")
    SIMULATORS_AND_SPORTS_EQUIPMENT("Simulators and sports equipment"),
    @XmlEnumValue("Game kinds of sports")
    GAME_KINDS_OF_SPORTS("Game kinds of sports"),
    @XmlEnumValue("Bicycles, electric bicycles and accessories")
    BICYCLES_ELECTRIC_BICYCLES_AND_ACCESSORIES("Bicycles, electric bicycles and accessories");
    private final String value;

    Category(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Category fromValue(String v) {
        for (Category c: Category.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
