//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.09 at 11:09:14 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/first", 
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
xmlns = {
        @XmlNs(prefix="sh", namespaceURI="http://nure.ua/bookShop")
})
package entity;

import javax.xml.bind.annotation.XmlNs;