//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.09 at 11:09:14 AM EET 
//

package entity;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import entity.SportInv;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "sportinv" })
@XmlRootElement(name = "SportShop")
public class SportShop {

	@XmlElement(required = true)
	protected List<SportInv> sportinv;

	public SportShop() {
		this.sportinv = new ArrayList<SportInv>();
	}

	public void addSportInv(SportInv sportinv) {
		this.sportinv.add(sportinv);
	}

	/**
	 * Gets the value of the sportinv property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the sportinv property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSportinv().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link SportInv
	 * }
	 * 
	 * 
	 */
	public List<SportInv> getSportinv() {
		if (sportinv == null) {
			sportinv = new ArrayList<SportInv>();
		}
		return this.sportinv;
	}

	@Override
	public String toString() {
		StringBuffer str = new StringBuffer();
		str.append("[\n");
		sportinv.forEach(el -> str.append(el.toString()).append("\n"));
		str.append("]");
		return str.toString();
	}

}
